# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15207feb4388088b7aa59e601315ba3632dda0550a6ae120d2fedea0095471a861abc5c58c3739cfcebff773d9103be3f108fee99bb73c28b22a0b0e55534482

test:
  secret_key_base: 139c0f260333e12b4f31da7fe30afdd403a4c079eca761e06ba0e27152dd5d40db77032c191251bb68c0c3f916aed7b5c5ef4518f4b40567b31860cbf00b1f51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
